import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header/Navbar';
import Footer from '@/components/Footer';
// import styles from '@/components/Header/Header.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Title page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
